In [4]:
import numpy as np
my_list=[1,2,3,4]
arr=np.array(my_list)
arr

array([1, 2, 3, 4])

In [9]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [17]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [18]:

np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [27]:
np.random.randint(9)

0

In [43]:
np.random.randint(0,1000,(4,4))

array([[578, 819, 889, 720],
       [669, 913,  39, 293],
       [561, 833, 323, 217],
       [894, 107, 625, 117]])

In [64]:
np.random.seed(10)
arr=np.random.randint(0,100,10)
arr

array([ 9, 15, 64, 28, 89, 93, 29,  8, 73,  0])

In [71]:
arr.max()

93

In [72]:
arr.sort()
arr

array([ 0,  8,  9, 15, 28, 29, 64, 73, 89, 93])

In [74]:
arr.min()

0

In [77]:
arr.mean()

40.8

In [79]:
arr.argmax()

9

In [81]:
arr.argmin()

0

In [83]:
arr.reshape(2,5)

array([[ 0,  8,  9, 15, 28],
       [29, 64, 73, 89, 93]])

In [89]:
mat=np.arange(0,100).reshape(10,10)
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [103]:
mat[0,:] #row
mat[:,0] #col
mat[1,1:]
mat[0:5,0:4]

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])